### ISSUE TITLE
Change polling time using REST

### ISSUE THREAD

**Issue by ajoaoff** [kytos/of_lldp#29]
It would be good to be able to change the `POLLING_TIME` setting without stopping Kytos, using a REST endpoint.

**Comment by gleybersonandrade** [comment]
This enhancement is awaiting discussion about etcd - [EP020](https://github.com/kytos/kytos/blob/master/docs/blueprints/EP020.rst)

**Comment by hdiogenes** [comment]
PR was accepted as a feature that enables change at runtime. Permanent change via REST will be available after the changes discussed in EP020.
