### ISSUE TITLE
No ping in mininet environment

### ISSUE THREAD

**Issue by cemsbr** [kytos/of_lldp#3]
Steps to reproduce:
1. Launch kytosd
2. Have only kytos/of_core and kytos/of_lldp enabled
3. For **proto** in OpenFlow13, OpenFlow10:
    1. sudo mn --topo linear,2 --mac --controller=remote,ip=127.0.0.1 --switch ovsk,protocols=**proto**
    2. h1 ping h2

**Comment by cemsbr** [comment]
#2 solves all code exceptions during this procedure.

**Comment by beraldoleal** [comment]
@cemsbr you are missing l2ls NApp.
