### ISSUE TITLE
Allow user to choose which interfaces to send LLDP packets

### ISSUE THREAD

**Issue by ajoaoff** [kytos/of_lldp#31]
This NApp always send LLDP packets to all interfaces of a switch. The user should be able to select only some interfaces to send the LLDP packets, reducing the CPU load on the switch.
To achieve this, REST methods must be created, and an attribute added to the interface. The REST methods must:

- List interfaces active to receive LLDP packets
- Add interfaces to receive LLDP
- Remove interfaces to receive LLDP

When sending the packets, the NApp should check that attribute to send or not the LLDP packet.
The default is to continue sending LLDP to all interfaces.

**Comment by cmagnobarbosa** [comment]
@ajoaoff  Reading about LLDP an improvement to this new feature is perhaps adding two other REST endpoints. First, one endpoint to disable lldp on all available interfaces and another endpoint to enable all. What do you think?

**Comment by ajoaoff** [comment]
@cmagnobarbosa Yes, you could do that. You could use the same endpoints but without the `<interface_id>`. One other suggestion: change the url from `/<interface_id>/enable` to `/enable/<interface_id>`. The same for the disable url.

**Comment by cmagnobarbosa** [comment]
Solved in PR #32
