### ISSUE TITLE
Disabling LLDP on a interface is not saved on storehouse

### ISSUE THREAD

**Issue by italovalcy** [kytos/of_lldp#49]
When the kytos user disable LLDP on a interface via REST API, this information should be saved via storehouse so it will consistent after stopping and starting kytos. Currently, this information is not saved.

Steps to reproduce:
1) Start Kytosd with of_lldp napp
2) disable LLDP for an interface:
``
curl -X POST -H "Content-Type: application/json" -d '{"interfaces": ["00:00:00:00:00:00:00:01:1"]}' http://localhost:8181/api/kytos/of_lldp/v1/interfaces/disable/
``
3) restart kytosd

Expected behavior:

The LLPD disabled on an interface should remain disabled.

Actual behavior:

The LLDP is enabled again on the interface.

Environment: kytos:2020.1b3 + kytos/of_lldp:0.1.4

**Comment by cmagnobarbosa** [comment]
Related: kytos/kytos#1127
