### ISSUE TITLE
When Kytos is started with -E the of_lldp flows are not created

### ISSUE THREAD

**Issue by italovalcy** [kytos/of_lldp#60]
When you start Kytos with the -E (enable all) option, the of_lldp does not create the flows.

Steps to reproduce:

1. Start Kytos with: `kytosd -E`
2. Start any topology with mininet (e.g. `mn --topo linear,3 --controller=remote`
3. wait a couple of seconds

Expected behavior: Kytos of_lldp should create the flows to send to the controller LLDP packets

Actual behavior: no flow is created
```
mininet> sh ovs-ofctl dump-flows s1
mininet> sh ovs-ofctl dump-flows s2
mininet> sh ovs-ofctl dump-flows s3
mininet>
```

**Comment by cmagnobarbosa** [comment]
Hello @italovalcy, I think this behavior is generated by the changes required by the consistency mechanism (https://github.com/kytos/flow_manager/pull/96), which resulted in changes to `of_lldp` (#56).  The`LLDP` flows are now installed by the ` flow_manager` after listening to an` kytos/topology.switch.enabled`(https://github.com/kytos/of_lldp/blob/master/main.py#L108~L137) event generated by the `topology`.

**Comment by josemauro** [comment]
I've just tested and the flows are not installed as @italovalcy described. So, following the ideas described by @cmagnobarbosa, I manually enabled switch 1. After that, the flows were installed and found in the switch 1. So I think we should discuss how to handle with a topology started with enabled devices.

**Comment by josemauro** [comment]
@cmagnobarbosa and I was discussing and one possible solution is make kytos/topology check if the switches are enable at bootstrap and send switch enabled events.
